// apps/reapp/src/app/app.tsx
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import styles from './app.module.css';
import NxWelcome from './nx-welcome';

export function App() {
  console.log('Hello', process.env['KATERINA']);

  return (
    <>
      <NxWelcome title="reapp" />
      <div />
    </>
  );
}

export default App;

// apps/ngapp/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'sb-env-nx-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'ngapp';

  constructor() {
    console.log('Hello', process.env['KATERINA']);
  }
}

<sb-env-nx-nx-welcome></sb-env-nx-nx-welcome>
